In [3]:
A = str(input("Enter A: "))
B = str(input("Enter B: "))
if A == 'hello' or B == 'hello':
    print("string involved")
if A > B:
    print("A bigger than B")
elif A == B:
    print("A equal B")
else:
    print("A smaller than B")
    print("Mohamed soffar")
    print("thanks!")

Enter A: hello
Enter B: hello
string involved
A equal B


In [1]:
print('Hello!')
i = 10
while(i<=10):
    if(i==2):
        print(i)
        break
    print(i)
    i -= 2

Hello!
10
8
6
4
2


In [4]:
end=7
result = 0
i = 0
while i <= end:
    result += i
    i += 1
print("result:",result)


result: 21


In [5]:
print('Hello!')
for i in range(10, 0, -2):
    print(i)


Hello!
10
8
6
4
2


In [12]:
result = end
for i in range(end):
    result += i
print(result)

21


In [1]:
q5 
a)
10
Outside of loop
9
Outside of loop
8
Outside of loop
7
Outside of loop
Breaking out of loop
b)
Infinite loop
c)
0
Foo!
4
8
12
16
Foo!
d)
letter # 0 is S
1
e)
H
e
e
l
l
l
o
!
!
done
f)

 How many times does H print out? (1 time) 
• How many times does e print out? Disregard the letters in the word done. (2 times)
• How many times does l print out?  (3 times)
• How many times does o print out? Disregard the letters in the word done.  (1 time)
• How many times does ! print out? (2 times)
• How many times does done print out? (1 time)


SyntaxError: unmatched ')' (<ipython-input-1-eb9d5be428db>, line 2)

In [17]:
s='azcbobobegghakl'
def counting_bobs(s):
    i=0
    count=0
    for i in range(0,len(s)):
        if s[i:(i+3)] =="bob":
            count +=1
    print("number of times bob occurs is : %s" % count )
counting_bobs(s)

number of times bob occurs is : 2


In [ ]:
q(8)
Output
Iteration 0; count is: 1
Iteration 1; count is: 12
Iteration 2; count is: 1
Iteration 3; count is: 12
Iteration 4; count is: 1 
    
How many times will the print statement be executed? 5
What is the largest value of the variable iteration that will be printed out (at
the print statement)? 4
What is the largest value of the variable count that will be printed out (at the
print statement)? 12
What is the smallest value of the variable count that will be printed out (at the
print statement)? 1

In [18]:
print("Please think of a number between 0 and 100!")
low = 0
high = 100
correct = False

while not correct:
    guess = int(low + (high - low)/2)
    print("Is your secret number ", guess, "?")
    hint = str(input("Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly."))
    if hint == "c":
        print("Game over. Your secret number was: " + str(guess))
        correct = True
    elif hint == "h":
        high = guess
    elif hint == "l":
        low = guess
    else:
        print("Sorry, I did not understand your input.")

Please think of a number between 0 and 100!
Is your secret number  50 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. h


Is your secret number  25 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. h


Is your secret number  12 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. l


Is your secret number  18 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. h


Is your secret number  15 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. l


Is your secret number  16 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. l


Is your secret number  17 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. h


Is your secret number  16 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. h


Is your secret number  16 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. h


Is your secret number  16 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. l


Is your secret number  16 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. l


Is your secret number  16 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. l


Is your secret number  16 ?


Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly. c


Game over. Your secret number was: 16


In [ ]:
a)
4
b)
19

In [22]:
def gcdIter(a, b):
    num = a
    if b < num:
        num = b
    while num > 1:
        if a % num == 0 and b % num == 0:
            break
        num -= 1
    return num
print(gcdIter(2, 12))
print(gcdIter(6, 12))
print(gcdIter(9, 12))
print(gcdIter(17, 12))

2
6
3
1


In [1]:
givenTuple = (2, 4, 5, 6, 2, 3, 4, 4, 7)
def countRepeated(givenTuple):
    count = 0
    for i in range(len(givenTuple)):
        if givenTuple[i] in givenTuple[i+1:] :
            count+= 1
    return count
print(countRepeated(givenTuple))

3


In [3]:
List1 = [1, 0, 1, 0, 0, 0, 2, -2, -2]
List2 = [2, 2]
def findSecondLargest(givenList):
    largest = max(givenList)
    secondLargest = givenList[0]
    count = 0
    for item in givenList:
        if item < largest:
            if item >= secondLargest:
                count += 1 
                secondLargest = item
    return secondLargest if count > 0 else None
print(findSecondLargest(List1))
print(findSecondLargest(List2))


1
None


In [4]:
List3 = [10, 20, 30, 20, 10, 50, 60, 40, 80, 50, 40]
removeDuplicate=set(List3)
print(list(removeDuplicate))

[40, 10, 80, 50, 20, 60, 30]


In [5]:
List4 = [10, 20, 30, 40, 40, 40, 70, 80, 99]
def countInRange(givenList, lower, upper):
    count = 0
    for item in givenList:
        if item >= lower and item<= upper:
            count += 1
    return count
print(countInRange(List4,40,100))

6


In [6]:
import numpy as np
arr = np.arange(start = 1,stop = 21,step = 1)
arr = np.reshape(arr,(4,5))
arrr =np.array([list(arr[1,:]),list(arr[3,:])])
print(arr)
print(arrr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [3]:
import numpy as np
odda = np.arange(start = 1,stop = 21,step = 2).reshape((2,5))
print(odda)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [1]:
import numpy as np
arr = np.arange(start = 1,stop = 13,step = 1).reshape((4,3))
print(arr)
rowsum = np.sum(arr,axis=1)
print("rowsum:",rowsum)
columnsum = np.sum(arr,axis=0)
print("columnsum:",columnsum)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
rowsum: [ 6 15 24 33]
columnsum: [22 26 30]


In [9]:
import numpy as np
arr = [[0.89372503,0.99865458,0.77120044],
[0.67632984,0.99990084,0.64110391],
[0.34845794,0.66557903,0.29031742]]
arr = np.array(arr)
norm = np.linalg.norm(arr)
normal = arr/norm
print(normal)

[[0.40342507 0.45078998 0.3481178 ]
 [0.30529346 0.45135254 0.28939257]
 [0.15729297 0.30044058 0.1310485 ]]


In [10]:
import numpy as np
arr = np.ones((4,4))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
